package: uikit_collection

version: '3.2.1'
vendor: '3.15.19'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/uikit_collection
info: 'FOR UIKIT Collection'

requires:
    redaxo: '>=5.13.0'
    php: '>=7.4'
         
