package: uikit_collection

version: '3.3.0-dev'
vendor: '3.16.26'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/uikit_collection
info: 'FOR UIKIT Collection'

requires:
    redaxo: '>=5.13.0'
    php: '>=7.4'
         
