# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: uikit_collection
version: '1.0.0-b2'
author: 'Friends Of REDAXO'
supportpage: https://github.com/klxm
info: 'FOR UIKIT Collection'
compile: 0

page:
    title: 'translate:title'
    perm: uikit[]
    icon: rex-icon fa-times-circle
    block: system
    subpages:
        module: {title: 'translate:module'}
        module_mform: {title: 'translate:module_mform_mblock'}
        templates: {title: 'translate:templates', icon: rex-icon fa-file-text-o}
        settings: {title: translate:settings, icon: rex-icon fa-cog}
        info:
            title: 'Info'
            itemclass: 'pull-right'
            subpages:
                info: { title: 'Info'}
                changelog: { title: 'translate:changelog'}
                lizenz: { title: 'translate:lizenz'}
requires:
    packages:
         video: '^1.0.0'
