package: uikit_collection
version: '3.0.0'
vendor: '3.10.1'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/uikit_collection
info: 'FOR UIKIT Collection'

requires:
    redaxo: '>=5.13.0'
    php: '>=7.2'
         
