package: uikit_collection

version: '4.0.0'
vendor: '3.17.11'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/uikit_collection
info: 'FOR UIKIT Collection'

default_config:
    path: 'assets/addons/uikit_collection/uikit/dist'
    prefix: ''

requires:
    redaxo: '>=5.15.0'
    php: '>=8.1'
         
