package: uikit_collection

version: '3.0.6'
vendor: '3.15.10'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/uikit_collection
info: 'FOR UIKIT Collection'

requires:
    redaxo: '>=5.13.0'
    php: '>=7.2'
         
