package: uikit_collection

version: '5.1.0'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/uikit_collection
info: 'FOR UIKIT Collection'

default_config:
    include_assets: false
    path: 'assets/addons/uikit_collection/uikit/dist'
    prefix: ''
    backend_path: 'assets/addons/uikit_collection/uikit/dist'
    backend_prefix: 'redaxo-theme'

requires:
    redaxo: '>=5.15.0'
    php: '>=8.1'
    
page:
    title: 'UIkit Collection'
    perm: admin
    icon: rex-icon fa-window-maximize
    subpages:
        config:
            title: 'Konfiguration'
            icon: rex-icon fa-cogs
        demo:
            title: 'Demo'
            icon: rex-icon fa-desktop
           

