name: Publish to REDAXO.org
on:
  release:
    types:
      - published

jobs:
  redaxo_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up PHP
        if: runner.os == 'Linux' && fileExists('composer.json')
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer Dependencies
        if: runner.os == 'Linux' && fileExists('composer.json')
        run: |
          composer install --no-dev
          
      - name: Publish to REDAXO.org
        if: runner.os == 'Linux' && fileExists('composer.json')
        uses: FriendsOfREDAXO/installer-action@v1
        with:
          myredaxo-username: ${{ secrets.MYREDAXO_USERNAME }}
          myredaxo-api-key: ${{ secrets.MYREDAXO_API_KEY }}
          description: ${{ github.event.release.body }}
          version: ${{ github.event.release.tag_name }}
